### ISSUE TITLE
Створити модель будівлі УКУ

### ISSUE THREAD

**Issue by LyubomyrD** [ucuapps/robert#1]

**Comment by AndriyPt** [comment]
@v-lavrushko everything looks good :+1:  Please make sure that robot is placed in the middle of building not laying upside down near wall 
![image](https://user-images.githubusercontent.com/10820297/36755913-460d3eb6-1c16-11e8-89c9-25ae9412baab.png)

I guess you could do that by changing pose of the building here https://github.com/ucuapps/robert/blob/F%231_ucu_building_model/robert_gazebo/worlds/ucu.world#L83
