### ISSUE TITLE
Beverage Web Server

### ISSUE THREAD

**Issue by AndriyPt** [ucuapps/robert#29]
Implement web server which fulfil the following requirements:
1. It should be located here https://github.com/ucuapps/robert/blob/kinetic-devel/robert_beverage/scripts/web_server
2. It should accept the following URL http://host:8080/beverage?x=1122&y=222
3. It should print coordinates received from URL
4. It should print error in console in case if not correct URL provided

After starting simulation it could be executed using the following command
```bash
rosrun robert_beverage web_server
```
In order to test it please install Firefox on you docker container using commands
```bash
sudo apt update
sudo apt install firefox -y
```

**Comment by v-lavrushko** [comment]
Thank you.
