### ISSUE TITLE
Docker saving files

### ISSUE THREAD

**Issue by sofiia-tesliuk** [ucuapps/robert#3]
Where to save world file of building in docker container for further usage?
`/bin/bash/workspace/robert ...`?

**Comment by AndriyPt** [comment]
World file should be stored here https://github.com/ucuapps/robert/tree/kinetic-devel/robert_gazebo/worlds . In perfect world it should be named ucu.world

**Comment by v-lavrushko** [comment]
where in computer memory should we save docker container and .png file (plan of building)?

**Comment by AndriyPt** [comment]
@sophia-tslk on your docker file system it should be this folder `/home/user/workspace/robert/base/src/robert/robert_gazebo/worlds`

**Comment by AndriyPt** [comment]
@v-lavrushko each question should be created as separate issue. And please either reformulate your questions or use Ukrainian :)
