### ISSUE TITLE
Бібліотека Python

### ISSUE THREAD

**Issue by v-lavrushko** [ucuapps/robert#33]
У свому коді я імпортую http.server. При запуску викидає таке:
```bash
Traceback (most recent call last):
  File "/home/user/workspace/robert/base/src/robert/robert_beverage/scripts/web_server", line 3, in <module>
    from http.server import *
ImportError: No module named http.server
```

**Comment by AndriyPt** [comment]
використовуйте `SimpleHTTPServer` як тут 
https://github.com/shadow-robot/robot_blockly/blob/master/scripts/pywebserver.py#L2
Цей пакунок має йти у бібліотеках по замовчуванню https://docs.python.org/2/library/simplehttpserver.html

**Comment by v-lavrushko** [comment]
![default](https://user-images.githubusercontent.com/29904652/37764242-de4c2272-2dc9-11e8-8a4b-703b2951a333.png)

**Comment by AndriyPt** [comment]
так виглядає, що погані налаштування PyCharm. По замовчуванню має бути Python 2.x тут є описано як https://stackoverflow.com/questions/15845929/how-to-set-the-python-2-preference-in-pycharm

Запускаю цей код у себе
```python
#!/usr/bin/env python
import rospy
import SimpleHTTPServer

rospy.init_node('web_server_node')
rospy.loginfo('Inside web_server script')

rospy.loginfo(dir(SimpleHTTPServer))
```

результат у консолі

```bash
┌─[user@385fb48d9515]─[~/workspace/robert/base]
└──╼ rosrun robert_beverage web_server 
[INFO] [1521714980.863953]: Inside web_server script
[INFO] [1521714980.864371]: ['BaseHTTPServer', 'SimpleHTTPRequestHandler', 'StringIO', '__all__', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__version__', 'cgi', 'mimetypes', 'os', 'posixpath', 'shutil', 'sys', 'test', 'urllib', 'urlparse']
```

**Comment by v-lavrushko** [comment]
Thank you.
