### ISSUE TITLE
git commit

### ISSUE THREAD

**Issue by sofiia-tesliuk** [ucuapps/robert#4]
```
>>> git commit -m "Created empty ucu world"
fatal: empty ident name (for <user@... (none)> ) not allowed
```
Володя комітить у гілку F#1_ucu_building_model і схоже, що у йому відмовлено у доступі. Чи може бути проблема у тому, що цю гілку створювали не ми?

**Comment by AndriyPt** [comment]
Софіє перше посилання у Google Search по помилці https://www.google.com.ua/search?q=fatal%3A+empty+ident+name+(for+%3Cuser%40...+(none)%3E+)+not+allowed&oq=fatal%3A+empty+ident+name+(for+%3Cuser%40...+(none)%3E+)+not+allowed&aqs=chrome..69i57j69i58.278j0j7&sourceid=chrome&ie=UTF-8 йде сюди https://bbs.archlinux.org/viewtopic.php?id=163624
А там сказано, що коли перший раз працюєте із Git вам треба встановити дві глобальні властивості:

`git config --global user.name "Sophia Tslk"`
`git config --global user.email "sophia@noemail.com"`

*Увага, інші учасники команди повинні встановити свої імена, а не Софія :)*
