### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by v-lavrushko** [ucuapps/robert#43]
I wrote this in package.xml:
```
<build_depend>python-qrencode</build_depend>
```
And then ran all required commands. But I still can't import it into my program. What am I doing wrong?

**Comment by AndriyPt** [comment]
@v-lavrushko it would be nice if you provide code which you trying to run and error which you are getting.
Also **python-qrencode** is not build time dependency it is run-time one. Python is an interpreted language :)

**Comment by v-lavrushko** [comment]
I didn't run any code. In my code I wrote an import command for python-qrencode and it's saying that this module doesn't exist. If I'm correct, Python doesj't support module names with "-".

**Comment by AndriyPt** [comment]
*it's saying* who or what is talking to you? :)
Please create sample code and run it and give me error. Sometimes IDE's (I am assuming you are talking to it) have wrong package search paths.

**Comment by v-lavrushko** [comment]
```
import rospy
import python-qrencode

rospy.init_node('generate_qr_code_node')
rospy.loginfo('Inside generate_qr_code script')

while not rospy.is_shutdown():
    x, y, host, port, filename = raw_input("Enter arguments: ").split()
    str_ = "http://{}:{}/beverage?x={}&y={}".format(host, port, x, y)
    qr = python-qrencode.encode(str_)
```
After running it:
```
└──╼ rosrun robert_beverage generate_qr_code 
  File "/home/user/workspace/robert/base/src/robert/robert_beverage/scripts/generate_qr_code", line 3
    import python-qrencode
                 ^
SyntaxError: invalid syntax

```

```
```

**Comment by AndriyPt** [comment]
@v-lavrushko **python-qrencode** is Debian package name. It is installing this https://github.com/Arachnid/pyqrencode/tree/master library. Name of the module is **qrencode**.
So you should use
```python
import rospy
import qrencode

rospy.init_node('generate_qr_code_node')
```

**Comment by v-lavrushko** [comment]
So in package file I should write <run_depend>qrencode...?

**Comment by AndriyPt** [comment]
Not quite right, please pay attention to details. [The devil is in the detail](https://en.wikipedia.org/wiki/The_devil_is_in_the_detail) :)
