### ISSUE TITLE
Web server and nav stack

### ISSUE THREAD

**Issue by v-lavrushko** [ucuapps/robert#67]
https://github.com/ucuapps/robert/blob/ecdd89ff635ebba1a06a6adef9a2b576c2260419/robert_beverage/scripts/web_server#L25
When I run my code, it get stuck on that line, and I don't know why. Do I have to run something?

**Comment by AndriyPt** [comment]
@v-lavrushko it will be nice in the future if you list what you have already started :)
You need to launch the following things:
* `roslaunch robert_launch simulation.launch`
* `roslaunch robert_launch navigation.launch`
* `rosrun robert_beverage web_server`

Also you could check if service which you are waiting for is running using ` rosservice list`. More details about rosservice command could be found here http://wiki.ros.org/rosservice

**Comment by v-lavrushko** [comment]
and how action server, that i have to communicate with, called?

**Comment by AndriyPt** [comment]
http://wiki.ros.org/actionlib_tutorials/Tutorials/Writing%20a%20Simple%20Action%20Client%20%28Python%29

**Comment by AndriyPt** [comment]
and this is an example how to call ROS service http://wiki.ros.org/ROS/Tutorials/WritingServiceClient%28python%29
