### ISSUE TITLE
Problems with web server

### ISSUE THREAD

**Issue by v-lavrushko** [ucuapps/robert#70]
Currently my code works in the next way: it will get the coordinates, wait until the robot is stopped moving and then show the web-page. But I think that web page should be shown before robot is in the place.

**Comment by AndriyPt** [comment]
It will be good. In this case you need to implement Web 2.0 approach. Create simple request to server  after page is loaded.

**Comment by AndriyPt** [comment]
you could create iframe which will load page in background. And nice page will appear right away. Please read this article for more details http://www.aaronpeters.nl/blog/iframe-loading-techniques-performance?%3E#onload
